/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function configure(configuration: Array<object>): boolean
export declare function getConfig(): object
export declare function getXprofilerConfig(): object
export declare function setXprofilerConfig(options: object): object
export declare function runCommandsListener(): unknown
export declare function info(component: string, message: string): void
export declare function error(component: string, message: string): void
export declare function debug(component: string, message: string): void
export declare function runLogBypass(): unknown
export declare function setHooks(): unknown
export declare function setup(): void
export declare function initMallopt(): void
export declare function checkSocketPath(): boolean
export declare function setHttpConfig(): void
export declare function addLiveRequest(): void
export declare function addCloseRequest(): void
export declare function addSentRequest(): void
export declare function addRequestTimeout(): void
export declare function addHttpStatusCode(): void
export declare function addHttpProfilingDetail(): void
