import * as React from 'react';
import { CSSProperties } from 'react';
import { AnimationManager } from './AnimationManager';
type CSSTransitionAnimateProps = {
    animationId: string;
    animationManager?: AnimationManager;
    duration?: number;
    begin?: number;
    easing?: string;
    isActive?: boolean | 'auto';
    canBegin?: boolean;
    from: string;
    to: string;
    attributeName: string;
    onAnimationStart?: () => void;
    onAnimationEnd?: () => void;
    children: (style: CSSProperties | undefined) => React.ReactNode;
};
export declare function CSSTransitionAnimate(outsideProps: CSSTransitionAnimateProps): React.ReactNode;
export {};
